errors on windows
beautifulsoup4 is missing
[✗] Error running module 'pllng': No module named 'bs4'

fix loading moduls in same folder
ModuleNotFoundError: No module named 'helpers', '_version'